import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#EAE8E1] overflow-y-auto min-h-screen">
        <div className="container mx-auto bg-[#F7F6F5] mt-6 justify-center rounded-t-xl  block">
          <Navbar />

          <div className="sticky top-0 z-10 overflow-visible">{children}</div>
        </div>
      </body>
      <GoogleAnalytics gaId="G-7FZD6MQ22T" />
    </html>
  );
}
